PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS restaurants (
 id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT DEFAULT '',
 phone TEXT DEFAULT '', phone_delivery TEXT DEFAULT '', whatsapp TEXT DEFAULT '',
 address TEXT DEFAULT '', google_maps TEXT DEFAULT '', hours TEXT DEFAULT '',
 logo TEXT DEFAULT '', main_image TEXT DEFAULT ''
);
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE,
 password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'admin',
 active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, description TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, category_id INTEGER NOT NULL REFERENCES categories(id), name TEXT NOT NULL, description TEXT DEFAULT '', price REAL NOT NULL, image TEXT DEFAULT '', available INTEGER NOT NULL DEFAULT 1, featured INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_name TEXT NOT NULL, phone TEXT NOT NULL, address TEXT DEFAULT '', notes TEXT DEFAULT '', total REAL NOT NULL, status TEXT NOT NULL DEFAULT 'pendiente', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_items (id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id INTEGER NOT NULL, quantity INTEGER NOT NULL, price REAL NOT NULL);
CREATE TABLE IF NOT EXISTS reservations (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, phone TEXT NOT NULL, guests INTEGER NOT NULL, date TEXT NOT NULL, time TEXT NOT NULL, notes TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'pendiente', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
